export interface ProductData {
  id: string;
  name: string;
  slug: string;
  description: string;
  price: number;
  compareAtPrice: number | null;
  category: string;
  brand: string;
  rating: number;
  reviewCount: number;
  inventory: number;
  colors: string[];
  features: string[];
  specs: Record<string, string>;
  aiMatch: number;
  image: string;
  badge: string | null;
}

export interface Category {
  id: string;
  name: string;
  slug: string;
  count: number;
}

export interface Brand {
  id: string;
  name: string;
  count: number;
}

export const categories: Category[] = [
  { id: "electronics", name: "Electronics", slug: "electronics", count: 8 },
  { id: "fashion", name: "Fashion", slug: "fashion", count: 4 },
  { id: "home", name: "Home & Kitchen", slug: "home", count: 4 },
  { id: "sports", name: "Sports & Outdoors", slug: "sports", count: 4 },
  { id: "beauty", name: "Beauty", slug: "beauty", count: 4 },
];

export const brands: Brand[] = [
  { id: "apple", name: "Apple", count: 2 },
  { id: "sony", name: "Sony", count: 2 },
  { id: "samsung", name: "Samsung", count: 2 },
  { id: "nintendo", name: "Nintendo", count: 1 },
  { id: "nike", name: "Nike", count: 2 },
  { id: "adidas", name: "Adidas", count: 2 },
  { id: "kitchenaid", name: "KitchenAid", count: 1 },
  { id: "ninja", name: "Ninja", count: 1 },
  { id: "bosch", name: "Bosch", count: 2 },
  { id: "le-creuset", name: "Le Creuset", count: 1 },
  { id: "the-north-face", name: "The North Face", count: 1 },
  { id: "technogym", name: "Technogym", count: 1 },
  { id: "patagonia", name: "Patagonia", count: 1 },
  { id: "garmin", name: "Garmin", count: 1 },
  { id: "clinique", name: "Clinique", count: 1 },
  { id: "la-mer", name: "La Mer", count: 1 },
  { id: "dyson", name: "Dyson", count: 2 },
  { id: "redken", name: "Redken", count: 1 },
];

export const products: ProductData[] = [
  {
    id: "1",
    name: "MacBook Pro 16-inch M4",
    slug: "macbook-pro-16-m4",
    description: "The most powerful MacBook Pro ever with the M4 chip, delivering extraordinary performance for demanding workflows. Featuring a stunning Liquid Retina XDR display, up to 22 hours of battery life, and a premium aluminum design.",
    price: 3499,
    compareAtPrice: 3799,
    category: "electronics",
    brand: "Apple",
    rating: 4.8,
    reviewCount: 2341,
    inventory: 18,
    colors: ["#404040", "#c0c0c0"],
    features: ["M4 Pro chip with 14-core CPU", "36GB unified memory", "1TB SSD storage", "16-inch Liquid Retina XDR display", "Thunderbolt 5 support", "Up to 22h battery life"],
    specs: { Processor: "Apple M4 Pro", Memory: "36GB Unified", Storage: "1TB SSD", Display: "16.2\" Liquid Retina XDR", Weight: "2.14 kg" },
    aiMatch: 97,
    image: "bg-gradient-to-br from-zinc-700 to-zinc-900",
    badge: "Best Seller",
  },
  {
    id: "2",
    name: "Sony WH-1000XM6",
    slug: "sony-wh-1000xm6",
    description: "Industry-leading noise canceling headphones with exceptional sound quality. The XM6 features the new QN1e processor for adaptive noise cancellation, 40-hour battery life, and premium comfort for all-day wear.",
    price: 399,
    compareAtPrice: 449,
    category: "electronics",
    brand: "Sony",
    rating: 4.7,
    reviewCount: 18452,
    inventory: 42,
    colors: ["#1a1a1a", "#f5f5f5", "#8B4513"],
    features: ["Industry-leading noise cancellation", "40-hour battery life", "Adaptive Sound Control", "Multipoint connection", "Hi-Res Audio support", "Quick charging (3min = 3h)"],
    specs: { Driver: "30mm", Frequency: "4Hz-40kHz", Battery: "40 hours", Weight: "254g", Codec: "LDAC, AAC, SBC" },
    aiMatch: 95,
    image: "bg-gradient-to-br from-zinc-800 to-zinc-950",
    badge: null,
  },
  {
    id: "3",
    name: "Samsung Odyssey OLED G8",
    slug: "samsung-odyssey-oled-g8",
    description: "32-inch 4K OLED gaming monitor with 240Hz refresh rate and 0.03ms response time. Quantum HDR delivers stunning contrast and vibrant colors.",
    price: 1299,
    compareAtPrice: 1499,
    category: "electronics",
    brand: "Samsung",
    rating: 4.6,
    reviewCount: 892,
    inventory: 7,
    colors: ["#1a1a2e"],
    features: ["32\" 4K OLED display", "240Hz refresh rate", "0.03ms response time", "AMD FreeSync Premium Pro", "Quantum HDR 2000", "Sleek metal design"],
    specs: { Size: "32\"", Resolution: "3840×2160", Refresh: "240Hz", Response: "0.03ms", HDR: "Quantum HDR 2000" },
    aiMatch: 92,
    image: "bg-gradient-to-br from-slate-800 to-slate-950",
    badge: "New",
  },
  {
    id: "4",
    name: "AirPods Max Type-C",
    slug: "airpods-max-usb-c",
    description: "Apple's over-ear headphones with precision-fit design, active noise cancellation, and spatial audio. Now with USB-C charging for universal compatibility.",
    price: 549,
    compareAtPrice: null,
    category: "electronics",
    brand: "Apple",
    rating: 4.4,
    reviewCount: 5631,
    inventory: 23,
    colors: ["#c0c0c0", "#404040", "#228B22", "#4169E1"],
    features: ["Active Noise Cancellation", "Spatial Audio with dynamic head tracking", "USB-C charging", "20-hour battery life", "Memory foam ear cushions", "Digital Crown for precise control"],
    specs: { Driver: "Apple-designed 40mm", "Battery Life": "20 hours", Charging: "USB-C", Weight: "386g", Audio: "Spatial Audio" },
    aiMatch: 88,
    image: "bg-gradient-to-br from-zinc-300 to-zinc-500",
    badge: null,
  },
  {
    id: "5",
    name: "Samsung Galaxy Book4 Ultra",
    slug: "samsung-galaxy-book4-ultra",
    description: "Ultra-premium laptop with Intel Core Ultra 9 processor and NVIDIA RTX 4070. 16-inch Dynamic AMOLED 2X display with 120Hz refresh rate.",
    price: 2399,
    compareAtPrice: 2699,
    category: "electronics",
    brand: "Samsung",
    rating: 4.5,
    reviewCount: 1247,
    inventory: 5,
    colors: ["#2d2d2d"],
    features: ["Intel Core Ultra 9 processor", "NVIDIA RTX 4070", "16\" Dynamic AMOLED 2X", "120Hz refresh rate", "32GB DDR5 RAM", "1TB NVMe SSD"],
    specs: { Processor: "Intel Core Ultra 9", GPU: "NVIDIA RTX 4070", Memory: "32GB DDR5", Storage: "1TB NVMe", Display: "16\" AMOLED 2X" },
    aiMatch: 90,
    image: "bg-gradient-to-br from-gray-800 to-gray-950",
    badge: "AI Pick",
  },
  {
    id: "6",
    name: "Sony A7R V",
    slug: "sony-a7r-v",
    description: "61MP full-frame mirrorless camera with AI-based autofocus system. 8-stop image stabilization and 8K video recording capability.",
    price: 3899,
    compareAtPrice: 4199,
    category: "electronics",
    brand: "Sony",
    rating: 4.9,
    reviewCount: 734,
    inventory: 3,
    colors: ["#1a1a1a"],
    features: ["61MP full-frame sensor", "AI-based autofocus", "8-stop IBIS", "8K 24fps video", "4-axis tilting screen", "Dual CFexpress Type A slots"],
    specs: { Sensor: "61MP Full-Frame", ISO: "100-32000", "Video": "8K 24fps", "AF Points": "693", Weight: "723g" },
    aiMatch: 93,
    image: "bg-gradient-to-br from-zinc-700 to-zinc-950",
    badge: "Premium",
  },
  {
    id: "7",
    name: "Dyson Airwrap i.d.",
    slug: "dyson-airwrap-id",
    description: "Intelligent multi-styler with Coanda airflow technology and app-connected personalized styling routines. New i.d. series learns your hair type.",
    price: 599,
    compareAtPrice: null,
    category: "beauty",
    brand: "Dyson",
    rating: 4.3,
    reviewCount: 8921,
    inventory: 14,
    colors: ["#c0c0c0", "#f5f5dc", "#ff1493"],
    features: ["Coanda airflow technology", "App-connected styling", "Heat control for hair health", "Interchangeable attachments", "3-speed airflow", "Intelligent heat control"],
    specs: { "Heat settings": "3", "Airflow": "3 speeds", Attachments: "6 included", Weight: "560g", Cable: "2.7m" },
    aiMatch: 85,
    image: "bg-gradient-to-br from-rose-200 to-rose-400",
    badge: null,
  },
  {
    id: "8",
    name: "Nintendo Switch 2",
    slug: "nintendo-switch-2",
    description: "The next generation of Nintendo gaming with enhanced performance, a larger display, and full backward compatibility with Switch games.",
    price: 449,
    compareAtPrice: null,
    category: "electronics",
    brand: "Nintendo",
    rating: 4.7,
    reviewCount: 342,
    inventory: 0,
    colors: ["#e60012", "#404040"],
    features: ["Enhanced performance", "8\" 1080p display", "Backward compatible", "Improved Joy-Con", "OLED screen", "Dock supports 4K"],
    specs: { Display: "8\" OLED 1080p", Storage: "256GB internal", "Battery": "6-9 hours", Weight: "420g", "Output": "4K via dock" },
    aiMatch: 96,
    image: "bg-gradient-to-br from-red-600 to-red-900",
    badge: "Pre-order",
  },
  {
    id: "9",
    name: "Nike Air Max Pulse",
    slug: "nike-air-max-pulse",
    description: "Premium lifestyle sneakers with visible Air cushioning and a sleek modern silhouette. Designed for all-day comfort with responsive foam midsole.",
    price: 189,
    compareAtPrice: 219,
    category: "fashion",
    brand: "Nike",
    rating: 4.5,
    reviewCount: 3456,
    inventory: 56,
    colors: ["#1a1a1a", "#f5f5f5", "#ff0000", "#0000ff"],
    features: ["Visible Air cushioning", "Mesh and synthetic upper", "Rubber outsole", "Padded collar", "Foam midsole", "Lace closure"],
    specs: { Upper: "Mesh/Synthetic", Closure: "Lace", Sole: "Rubber", "Air unit": "180-degree visible", Weight: "340g" },
    aiMatch: 91,
    image: "bg-gradient-to-br from-neutral-800 to-neutral-950",
    badge: "Trending",
  },
  {
    id: "10",
    name: "Adidas Ultraboost Light",
    slug: "adidas-ultraboost-light",
    description: "Ultra-lightweight running shoes with the lightest Ultraboost foam ever. 30% lighter than previous generations with energy-returning technology.",
    price: 189,
    compareAtPrice: null,
    category: "fashion",
    brand: "Adidas",
    rating: 4.6,
    reviewCount: 5678,
    inventory: 34,
    colors: ["#1a1a1a", "#ffffff", "#cc0000"],
    features: ["Ultraboost Light foam", "Continental rubber outsole", "Primeknit+ upper", "Heel counter", "Stretchweb outsole", "Energy-returning"],
    specs: { Upper: "Primeknit+", Midsole: "Ultraboost Light", Outsole: "Continental Rubber", Drop: "10mm", Weight: "295g" },
    aiMatch: 89,
    image: "bg-gradient-to-br from-slate-700 to-slate-950",
    badge: null,
  },
  {
    id: "11",
    name: "Nike Tech Fleece Collection",
    slug: "nike-tech-fleece",
    description: "Premium cotton fleece hoodie with clean paneling and modern fit. Signature Tech Fleece fabric provides warmth without bulk.",
    price: 129,
    compareAtPrice: null,
    category: "fashion",
    brand: "Nike",
    rating: 4.4,
    reviewCount: 12450,
    inventory: 89,
    colors: ["#1a1a1a", "#808080", "#4169E1", "#8B4513"],
    features: ["Tech Fleece fabric", "Paneled design", "Zippered pocket", "Ribbed cuffs and hem", "Adjustable hood", "Machine washable"],
    specs: { Material: "Cotton/Polyester Fleece", Fit: "Modern", Pockets: "Zippered side", Care: "Machine wash", Weight: "410g" },
    aiMatch: 84,
    image: "bg-gradient-to-br from-slate-600 to-slate-900",
    badge: "Popular",
  },
  {
    id: "12",
    name: "Adidas Stan Smith Lux",
    slug: "adidas-stan-smith-lux",
    description: "Reimagined iconic tennis shoe with premium leather construction and subtle gold detailing. A timeless silhouette elevated with luxury materials.",
    price: 149,
    compareAtPrice: 179,
    category: "fashion",
    brand: "Adidas",
    rating: 4.3,
    reviewCount: 3240,
    inventory: 28,
    colors: ["#f5f5f5", "#1a1a1a", "#006400"],
    features: ["Premium leather upper", "Gold foil branding", "Perforated 3-Stripes", "Leather lining", "Rubber cupsole", "Ortholite insole"],
    specs: { Upper: "Premium Leather", Lining: "Leather", Sole: "Rubber cupsole", Closure: "Lace", "Made in": "Italy" },
    aiMatch: 82,
    image: "bg-gradient-to-br from-stone-200 to-stone-400",
    badge: null,
  },
  {
    id: "13",
    name: "KitchenAid Artisan Stand Mixer",
    slug: "kitchenaid-artisan-mixer",
    description: "Iconic stand mixer with 5-quart stainless steel bowl and 10-speed settings. The kitchen essential for baking enthusiasts and professional chefs alike.",
    price: 499,
    compareAtPrice: 549,
    category: "home",
    brand: "KitchenAid",
    rating: 4.8,
    reviewCount: 28761,
    inventory: 15,
    colors: ["#cc0000", "#f5f5f5", "#1a1a1a", "#4169E1", "#50C878"],
    features: ["5-quart stainless bowl", "10 speeds", "Tilt-head design", "Power hub for attachments", "Die-cast metal construction", "Dishwasher-safe bowl"],
    specs: { Capacity: "5-quart", Speeds: "10", Bowl: "Stainless Steel", Construction: "Die-cast Metal", Watts: "325", Weight: "11.8 kg" },
    aiMatch: 94,
    image: "bg-gradient-to-br from-red-500 to-red-700",
    badge: "Best Seller",
  },
  {
    id: "14",
    name: "Ninja Creami Professional",
    slug: "ninja-creami-pro",
    description: "Professional-grade ice cream maker that creates premium frozen treats from any base. Make ice cream, sorbet, gelato, and milkshakes at home.",
    price: 249,
    compareAtPrice: 299,
    category: "home",
    brand: "Ninja",
    rating: 4.4,
    reviewCount: 12450,
    inventory: 31,
    colors: ["#404040"],
    features: ["7 one-touch programs", "Professional creaming technology", "Makes ice cream, sorbet, gelato", "Includes 3 pints", "BPA-free pint containers", "Easy-clean cycle"],
    specs: { Programs: "7", Capacity: "1 pint per batch", Power: "1600W", Containers: "3 pints included", Weight: "4.5 kg" },
    aiMatch: 86,
    image: "bg-gradient-to-br from-gray-600 to-gray-900",
    badge: null,
  },
  {
    id: "15",
    name: "Bosch 800 Series Dishwasher",
    slug: "bosch-800-dishwasher",
    description: "Ultra-quiet dishwasher with CrystalDry technology that transforms moisture into heat for perfectly dried dishes. 44 dBA — whisper quiet.",
    price: 1399,
    compareAtPrice: 1599,
    category: "home",
    brand: "Bosch",
    rating: 4.7,
    reviewCount: 3420,
    inventory: 8,
    colors: ["#1a1a1a", "#f5f5f5"],
    features: ["CrystalDry technology", "44 dBA ultra-quiet", "Flexible 3rd rack", "HomeConnect app", "Sanitize option", "Energy Star certified"],
    specs: { "dBA": "44", Capacity: "14 place settings", Cycles: "5", Options: "4", "Energy Star": "Certified", Weight: "43 kg" },
    aiMatch: 91,
    image: "bg-gradient-to-br from-zinc-700 to-zinc-950",
    badge: "Premium",
  },
  {
    id: "16",
    name: "Le Creuset Dutch Oven",
    slug: "le-creuset-dutch-oven",
    description: "Premium enameled cast iron dutch oven with superior heat distribution. The iconic French cookware that lasts generations.",
    price: 429,
    compareAtPrice: null,
    category: "home",
    brand: "Le Creuset",
    rating: 4.9,
    reviewCount: 18762,
    inventory: 12,
    colors: ["#cc0000", "#f5f5f5", "#4169E1", "#50C878", "#ff8c00"],
    features: ["Enameled cast iron", "Superior heat retention", "Oven safe to 500°F", "Durable enamel interior", "Integrated lid spikes", "Wide handles for easy grip"],
    specs: { Material: "Enameled Cast Iron", Capacity: "5.5-quart", "Oven Safe": "500°F", Weight: "5.4 kg", Warranty: "Limited Lifetime" },
    aiMatch: 93,
    image: "bg-gradient-to-br from-red-600 to-red-800",
    badge: "Iconic",
  },
  {
    id: "17",
    name: "The North Face Thermoball Eco",
    slug: "north-face-thermoball-eco",
    description: "Synthetic insulated jacket with Thermoball Eco technology for warmth even when wet. Lightweight, packable, and made from recycled materials.",
    price: 229,
    compareAtPrice: null,
    category: "sports",
    brand: "The North Face",
    rating: 4.5,
    reviewCount: 4567,
    inventory: 37,
    colors: ["#1a1a1a", "#4169E1", "#cc0000", "#006400"],
    features: ["Thermoball Eco insulation", "Water-resistant finish", "Packable design", "Recycled materials", "Zippered pockets", "Adjustable hem"],
    specs: { Insulation: "Thermoball Eco", Shell: "Water-resistant", Weight: "370g", Packable: "Yes", Pockets: "5", Fill: "100% Recycled" },
    aiMatch: 87,
    image: "bg-gradient-to-br from-blue-800 to-blue-950",
    badge: null,
  },
  {
    id: "18",
    name: "Technogym Run Evolve",
    slug: "technogym-run-evolve",
    description: "Premium connected treadmill with 22-inch HD touchscreen and live fitness classes. Advanced cushioning system reduces joint impact by 25%.",
    price: 4499,
    compareAtPrice: 4999,
    category: "sports",
    brand: "Technogym",
    rating: 4.6,
    reviewCount: 342,
    inventory: 4,
    colors: ["#1a1a1a", "#f5f5f5"],
    features: ["22\" HD touchscreen", "Live fitness classes", "Advanced cushioning", "Up to 20km/h speed", "-2% to 15% incline", "Bluetooth connectivity"],
    specs: { Screen: "22\" HD Touch", Speed: "0.5-20 km/h", Incline: "-2% to 15%", Motor: "4.0 CHP", Cushioning: "SoftGel", Weight: "145 kg" },
    aiMatch: 95,
    image: "bg-gradient-to-br from-slate-800 to-slate-950",
    badge: "Premium",
  },
  {
    id: "19",
    name: "Patagonia Better Sweater",
    slug: "patagonia-better-sweater",
    description: "Fair Trade Certified fleece jacket made from 100% recycled polyester. Warm, durable, and responsibly manufactured.",
    price: 169,
    compareAtPrice: null,
    category: "sports",
    brand: "Patagonia",
    rating: 4.4,
    reviewCount: 8934,
    inventory: 64,
    colors: ["#1a1a1a", "#006400", "#8B0000", "#4169E1"],
    features: ["100% recycled polyester", "Fair Trade Certified", "Zip-in compatibility", "Microbeard fleece", "Nap-proof face fabric", "Zippered hand pockets"],
    specs: { Material: "100% Recycled Polyester", Weight: "580g", Pockets: "2 hand, 1 chest", Care: "Machine wash", "Fair Trade": "Certified" },
    aiMatch: 83,
    image: "bg-gradient-to-br from-green-800 to-green-950",
    badge: "Eco",
  },
  {
    id: "20",
    name: "Garmin Fenix 8 Pro",
    slug: "garmin-fenix-8-pro",
    description: "Ultimate multisport GPS watch with AMOLED display, solar charging, and advanced training metrics. Built for endurance athletes.",
    price: 999,
    compareAtPrice: 1099,
    category: "sports",
    brand: "Garmin",
    rating: 4.7,
    reviewCount: 2134,
    inventory: 9,
    colors: ["#1a1a1a", "#c0c0c0"],
    features: ["1.4\" AMOLED display", "Solar charging", "Multi-band GPS", "TopoActive maps", "Training readiness", "Up to 29 days battery"],
    specs: { Display: "1.4\" AMOLED", GPS: "Multi-band", "Battery": "29 days (smartwatch)", Water: "10 ATM", Maps: "TopoActive", Weight: "96g" },
    aiMatch: 94,
    image: "bg-gradient-to-br from-slate-700 to-slate-950",
    badge: "New",
  },
  {
    id: "21",
    name: "Clinique Clarifying Lotion",
    slug: "clinique-clarifying-lotion",
    description: "Expertly formulated toner that gently exfoliates and refines skin texture. Removes dead skin cells to reveal a smoother, brighter complexion.",
    price: 29,
    compareAtPrice: null,
    category: "beauty",
    brand: "Clinique",
    rating: 4.2,
    reviewCount: 34567,
    inventory: 120,
    colors: ["#f5f5f5"],
    features: ["Gentle exfoliation", "Alcohol-free", "Oil-free formula", "Dermatologist developed", "Allergy tested", "Non-comedogenic"],
    specs: { Size: "200ml", Type: "Exfoliating Toner", "Skin Type": "All types", "Active": "Salicylic Acid 0.5%", "Free From": "Alcohol, Oil" },
    aiMatch: 78,
    image: "bg-gradient-to-br from-cyan-200 to-cyan-400",
    badge: null,
  },
  {
    id: "22",
    name: "Dyson Supersonic r",
    slug: "dyson-supersonic-r",
    description: "Reimagined professional hair dryer with intelligent heat control and a compact new motor. The Supersonic r is 30% smaller while delivering the same powerful airflow.",
    price: 499,
    compareAtPrice: null,
    category: "beauty",
    brand: "Dyson",
    rating: 4.5,
    reviewCount: 6789,
    inventory: 11,
    colors: ["#c0c0c0", "#ff1493"],
    features: ["Intelligent heat control", "Compact V10 motor", "Air Multiplier technology", "Magnetic attachments", "4 heat settings", "3 airflow speeds"],
    specs: { Motor: "V10 Hyperdymium", Power: "1200W", Weight: "320g", Attachments: "5 included", Cable: "2.8m", "Heat Settings": "4" },
    aiMatch: 90,
    image: "bg-gradient-to-br from-rose-300 to-rose-500",
    badge: "New",
  },
  {
    id: "23",
    name: "La Mer Crème de la Mer",
    slug: "la-mer-creme",
    description: "The legendary moisturizer with Miracle Broth, a ferment of sea kelp and minerals. Transforms skin visibly with renewed radiance and resilience.",
    price: 445,
    compareAtPrice: null,
    category: "beauty",
    brand: "La Mer",
    rating: 4.7,
    reviewCount: 12345,
    inventory: 6,
    colors: ["#f5f5f5"],
    features: ["Miracle Broth ferment", "Deep moisture renewal", "Visible radiance", "Calming comfort", "Limited-edition jar", "Dermatologist tested"],
    specs: { Size: "60ml", Type: "Moisturizer", Key: "Miracle Broth", "Skin Type": "All types", Texture: "Rich cream", Origin: "Made in USA" },
    aiMatch: 87,
    image: "bg-gradient-to-br from-teal-200 to-teal-400",
    badge: "Luxury",
  },
  {
    id: "24",
    name: "Redken Acidic Bonding Concentrate",
    slug: "redken-acidic-bonding",
    description: "Professional bonding treatment that repairs hair from within. With acidic pH and bonding care complex for stronger, healthier-looking hair.",
    price: 38,
    compareAtPrice: null,
    category: "beauty",
    brand: "Redken",
    rating: 4.3,
    reviewCount: 8923,
    inventory: 44,
    colors: ["#f5f5f5"],
    features: ["Bonding care complex", "Acidic pH 4.5", "Repairs broken bonds", "Color-safe formula", "Sulfate-free", "Suitable for all hair types"],
    specs: { Size: "250ml", Type: "Bonding Treatment", pH: "4.5", Free: "Sulfates, Parabens", Use: "Weekly treatment", Results: "In 1 use" },
    aiMatch: 81,
    image: "bg-gradient-to-br from-purple-300 to-purple-500",
    badge: null,
  },
];

export const priceRange = { min: 0, max: 5000 };

export function getProductBySlug(slug: string): ProductData | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductById(id: string): ProductData | undefined {
  return products.find((p) => p.id === id);
}

export function getRelatedProducts(product: ProductData, count = 4): ProductData[] {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, count);
}
